spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://ec2-23-22-156-110.compute-1.amazonaws.com:5432/d8frvclajntbpq
    username: uwltyvxxxnqfky
    password: 956bcfa743a877b460ef637b80cdf2d1215f5c2d912e7e3b9945889214589838
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jackson:
    time-zone: America/Sao_Paulo

  jpa:
    hibernate:
      ddl-auto: none
      format_sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob.non_contextual_creation: true

server:
  port: 8092

app-config:
  agromonitoring_api_key: ae32b9044d0336489e22e887fb4e4f43
  integracao:
    poligono:
      url: http://api.agromonitoring.com/agro/1.0/polygons?appid=${app-config.agromonitoring_api_key}
    previsao:
      url: http://api.agromonitoring.com/agro/1.0/weather/